version: '3'

services:
  php:
    image: webdevops/php-nginx-dev:8.0-alpine
    volumes:
      # data containers containing the actual PHP code
      - .:/app:ro
      - ./nginx_app.conf:/opt/docker/etc/nginx/vhost.common.conf.d/nginx_app.conf
    networks:
      - database
    environment:
      WEB_DOCUMENT_ROOT: "/app/src"
      PHP_DEBUGGER: "xdebug3"
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
      XDEBUG_DISCOVER_CLIENT_HOST: 1
    ports: 
      - 8888:80
    expose:
      - "9003"
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "database:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      ADMINER_DEFAULT_SERVER: db
    networks:
      - database

volumes:
  database:

networks:
  database: